// frontend/src/lib/LinearSpinner.svelte
<script>
import { onDestroy, onMount } from "svelte";

const { sides = 20, onRollComplete = () => {} } = $props();
const REPEATS = 5;

let isSpinning = $state(false);
let finalValue = $state(null);
let container;
let viewportWidth = $state(0);
let itemWidth = $state(0);
let centerOffsetPx = $state(0);
let rafId = null;
let startTime = 0;
let durationMs = 0;
let startPos = 0;
let endPos = 0;
let currentPos = $state(0);
let lastTickIndex = -1;
let audioCtx = null;

const clampSides = (n) => Math.max(2, Math.floor(n || 2));
const easeOutCubic = (t) => 1 - (1 - t) ** 3;
const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;

function cancelRaf() {
	if (rafId != null) {
		cancelAnimationFrame(rafId);
		rafId = null;
	}
}

function measure() {
	if (!container) return;
	const rect = container.getBoundingClientRect();
	viewportWidth = rect.width || 0;
	itemWidth = viewportWidth;
	centerOffsetPx = (viewportWidth - itemWidth) / 2;
}

function ensureAudio() {
	if (!audioCtx) {
		try {
			audioCtx = new (window.AudioContext || window.webkitAudioContext)();
		} catch {
			audioCtx = null;
		}
	}
	return audioCtx;
}

function playTick() {
	const ctx = ensureAudio();
	if (!ctx) return;
	const now = ctx.currentTime;

	const noise = ctx.createBufferSource();
	const buffer = ctx.createBuffer(1, ctx.sampleRate * 0.03, ctx.sampleRate);
	const data = buffer.getChannelData(0);
	for (let i = 0; i < data.length; i++) {
		data[i] = (Math.random() * 2 - 1) * (1 - i / data.length);
	}
	noise.buffer = buffer;

	const filter = ctx.createBiquadFilter();
	filter.type = "highpass";
	filter.frequency.value = 1200;

	const gain = ctx.createGain();
	gain.gain.setValueAtTime(0.06, now);
	gain.gain.exponentialRampToValueAtTime(0.001, now + 0.04);

	noise.connect(filter);
	filter.connect(gain);
	gain.connect(ctx.destination);

	noise.start(now);
	noise.stop(now + 0.05);
}

onMount(() => {
	measure();
	const ro = new ResizeObserver(() => measure());
	if (container) ro.observe(container);
	return () => ro.disconnect();
});

onDestroy(() => cancelRaf());

export function roll() {
	if (isSpinning) return;
	const totalSides = clampSides(sides);
	measure();
	if (itemWidth === 0) return;

	finalValue = randomInt(1, totalSides);

	const startLoop = Math.floor(REPEATS / 2) * totalSides;
	const startIndex = startLoop + randomInt(0, totalSides - 1);
	const extraLoops = 2 + Math.floor(Math.random() * 2);
	const desiredIndexMod = (finalValue - 1 + totalSides) % totalSides;
	const delta = (((desiredIndexMod - (startIndex % totalSides)) % totalSides) + totalSides) % totalSides;
	const targetIndex = startIndex + extraLoops * totalSides + delta;

	startPos = startIndex;
	endPos = targetIndex;
	currentPos = startPos;
	lastTickIndex = Math.floor(currentPos);
	durationMs = 2400 + Math.random() * 900;
	startTime = performance.now();
	isSpinning = true;

	cancelRaf();
	rafId = requestAnimationFrame(step);
}

function step(now) {
	const elapsed = now - startTime;
	const t = Math.min(1, elapsed / durationMs);
	const eased = easeOutCubic(t);
	currentPos = startPos + (endPos - startPos) * eased;

	const ci = Math.floor(currentPos);
	if (ci !== lastTickIndex) {
		lastTickIndex = ci;
		playTick();
	}

	if (t < 1) {
		rafId = requestAnimationFrame(step);
		return;
	}

	currentPos = endPos;
	isSpinning = false;
	onRollComplete(finalValue);
}
</script>

<div bind:this={container} class="w-full h-full flex items-center justify-center overflow-hidden select-none">
	{#if isSpinning}
		<div class="relative w-full" style="height: clamp(6rem, 35vh, 24rem);">
			<div class="absolute inset-0 flex items-center">
				<div class="flex items-center" style="transform: translateX(-{currentPos * itemWidth - centerOffsetPx}px); transition: transform 0.02s linear; will-change: transform;">
					{#each Array(REPEATS * clampSides(sides)) as _, idx}
						<div class="shrink-0 flex items-center justify-center" style="width: {itemWidth}px;">
							<div style="font-size: clamp(5rem, 26vw, 20rem); line-height: 1;">
								{(idx % clampSides(sides)) + 1}
							</div>
						</div>
					{/each}
				</div>
			</div>
		</div>
	{:else}
		<div class="w-full" style="height: clamp(6rem, 35vh, 24rem); display: flex; align-items: center; justify-content: center;">
			<div style="font-size: clamp(5rem, 26vw, 20rem); line-height: 1;">
				{finalValue ?? 1}
			</div>
		</div>
	{/if}
</div>

// frontend/src/components/LinearSpinner.jsx
import PropTypes from 'prop-types';
import {
	forwardRef,
	useCallback,
	useEffect,
	useImperativeHandle,
	useRef,
	useState,
} from 'react';

const clampSides = (n) => Math.max(2, Math.floor(n || 2));
const easeOutQuart = (t) => 1 - (1 - t) ** 4;
const randomInt = (min, max) =>
	Math.floor(Math.random() * (max - min + 1)) + min;

const LinearSpinner = forwardRef(
	({ sides = 20, onRollComplete = () => {} }, ref) => {
		const [isSpinning, setIsSpinning] = useState(false);
		const [finalValue, setFinalValue] = useState(null);
		const [displayNumbers, setDisplayNumbers] = useState([]);

		const containerRef = useRef(null);
		const rafIdRef = useRef(null);
		const startTimeRef = useRef(0);
		const durationMsRef = useRef(0);
		const fullSequenceRef = useRef([]);
		const currentScrollRef = useRef(0);
		const targetScrollRef = useRef(0);
		const lastTickIndexRef = useRef(-1);
		const audioCtxRef = useRef(null);
		const itemWidthRef = useRef(200);

		const cancelRaf = useCallback(() => {
			if (rafIdRef.current != null) {
				cancelAnimationFrame(rafIdRef.current);
				rafIdRef.current = null;
			}
		}, []);

		const ensureAudio = () => {
			if (!audioCtxRef.current) {
				try {
					const AudioContextClass =
						window.AudioContext || window.webkitAudioContext;
					audioCtxRef.current = new AudioContextClass();
				} catch {
					audioCtxRef.current = null;
				}
			}
			return audioCtxRef.current;
		};

		const playTick = () => {
			const ctx = ensureAudio();
			if (!ctx) return;
			const now = ctx.currentTime;

			const noise = ctx.createBufferSource();
			const buffer = ctx.createBuffer(
				1,
				ctx.sampleRate * 0.025,
				ctx.sampleRate,
			);
			const data = buffer.getChannelData(0);
			for (let i = 0; i < data.length; i++) {
				data[i] = (Math.random() * 2 - 1) * (1 - i / data.length);
			}
			noise.buffer = buffer;

			const filter = ctx.createBiquadFilter();
			filter.type = 'highpass';
			filter.frequency.value = 1400;

			const gain = ctx.createGain();
			gain.gain.setValueAtTime(0.05, now);
			gain.gain.exponentialRampToValueAtTime(0.001, now + 0.03);

			noise.connect(filter);
			filter.connect(gain);
			gain.connect(ctx.destination);

			noise.start(now);
			noise.stop(now + 0.04);
		};

		const generateSpinSequence = (totalSides, targetNumber) => {
			let sequenceLength;
			if (totalSides <= 20) {
				sequenceLength = 40;
			} else if (totalSides <= 100) {
				sequenceLength = 50;
			} else if (totalSides <= 1000) {
				sequenceLength = 60;
			} else {
				sequenceLength = 70;
			}

			const sequence = [];

			const phase1Count = Math.floor(sequenceLength * 0.3);
			for (let i = 0; i < phase1Count; i++) {
				sequence.push(randomInt(1, totalSides));
			}

			const phase2Count = Math.floor(sequenceLength * 0.4);
			const range = Math.max(10, Math.floor(totalSides * 0.2));
			for (let i = 0; i < phase2Count; i++) {
				const min = Math.max(1, targetNumber - range);
				const max = Math.min(totalSides, targetNumber + range);
				sequence.push(randomInt(min, max));
			}

			const phase3Count = Math.floor(sequenceLength * 0.2);
			const narrowRange = Math.max(3, Math.floor(totalSides * 0.05));
			for (let i = 0; i < phase3Count; i++) {
				const min = Math.max(1, targetNumber - narrowRange);
				const max = Math.min(totalSides, targetNumber + narrowRange);
				sequence.push(randomInt(min, max));
			}

			sequence.push(targetNumber);

			return sequence;
		};

		const updateVisibleNumbers = useCallback((scrollPosition) => {
			const sequence = fullSequenceRef.current;
			if (sequence.length === 0) return;

			const itemWidth = itemWidthRef.current;
			const centerIndex = scrollPosition / itemWidth;

			const windowSize = 15;
			const startIdx = Math.max(
				0,
				Math.floor(centerIndex) - Math.floor(windowSize / 2),
			);
			const endIdx = Math.min(sequence.length, startIdx + windowSize);

			const visibleNums = [];
			for (let i = startIdx; i < endIdx; i++) {
				visibleNums.push({
					value: sequence[i],
					index: i,
					position: i * itemWidth,
				});
			}

			setDisplayNumbers(visibleNums);
		}, []);

		const step = (now) => {
			const elapsed = now - startTimeRef.current;
			const t = Math.min(1, elapsed / durationMsRef.current);
			const eased = easeOutQuart(t);

			const currentScroll =
				currentScrollRef.current +
				(targetScrollRef.current - currentScrollRef.current) * eased;

			updateVisibleNumbers(currentScroll);

			const itemWidth = itemWidthRef.current;
			const currentIndex = Math.floor(currentScroll / itemWidth);
			if (
				currentIndex !== lastTickIndexRef.current &&
				currentIndex < fullSequenceRef.current.length
			) {
				lastTickIndexRef.current = currentIndex;
				playTick();
			}

			if (t < 1) {
				rafIdRef.current = requestAnimationFrame(step);
				return;
			}

			setIsSpinning(false);
			onRollComplete(finalValue);
		};

		const roll = () => {
			if (isSpinning) return;

			const totalSides = clampSides(sides);
			const newFinalValue = randomInt(1, totalSides);
			setFinalValue(newFinalValue);

			const sequence = generateSpinSequence(totalSides, newFinalValue);
			fullSequenceRef.current = sequence;

			const itemWidth = itemWidthRef.current;
			currentScrollRef.current = 0;
			targetScrollRef.current = (sequence.length - 1) * itemWidth;

			updateVisibleNumbers(0);

			lastTickIndexRef.current = -1;
			durationMsRef.current = 2000 + Math.random() * 800;
			startTimeRef.current = performance.now();
			setIsSpinning(true);

			cancelRaf();
			rafIdRef.current = requestAnimationFrame(step);
		};

		useImperativeHandle(ref, () => ({
			roll,
		}));

		useEffect(() => {
			return () => cancelRaf();
		}, [cancelRaf]);

		return (
			<div
				ref={containerRef}
				className="w-full h-full flex items-center justify-center overflow-hidden select-none"
			>
				{isSpinning ? (
					<div
						className="relative w-full overflow-hidden"
						style={{ height: 'clamp(6rem, 35vh, 24rem)' }}
					>
						<div
							className="absolute left-1/2 top-0 bottom-0 w-1 bg-gradient-to-b from-transparent via-blue-500 to-transparent opacity-30 pointer-events-none z-10"
							style={{ transform: 'translateX(-50%)' }}
						/>

						<div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-slate-50 to-transparent pointer-events-none z-10" />
						<div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-slate-50 to-transparent pointer-events-none z-10" />

						<div className="absolute inset-0 flex items-center">
							<div className="relative w-full h-full flex items-center">
								{displayNumbers.map((item) => {
									const currentScroll = currentScrollRef.current;
									const targetScroll = targetScrollRef.current;
									const t = Math.min(
										1,
										(performance.now() - startTimeRef.current) /
											durationMsRef.current,
									);
									const eased = easeOutQuart(t);
									const interpolatedScroll =
										currentScroll + (targetScroll - currentScroll) * eased;

									const offset = item.position - interpolatedScroll;

									const distanceFromCenter = Math.abs(offset);
									const maxDistance = 400;
									const opacity = Math.max(
										0.2,
										1 - distanceFromCenter / maxDistance,
									);

									const scale = Math.max(
										0.6,
										1 - Math.abs(distanceFromCenter) / 800,
									);

									return (
										<div
											key={`${item.index}-${item.value}`}
											className="absolute flex items-center justify-center"
											style={{
												left: '50%',
												transform: `translateX(calc(-50% + ${offset}px)) scale(${scale})`,
												width: `${itemWidthRef.current}px`,
												fontSize: 'clamp(4rem, 20vw, 16rem)',
												lineHeight: 1,
												fontWeight: 700,
												color: '#1e293b',
												opacity: opacity,
												transition: t >= 1 ? 'transform 0.3s ease-out' : 'none',
											}}
										>
											{item.value}
										</div>
									);
								})}
							</div>
						</div>
					</div>
				) : (
					<div
						className="w-full"
						style={{
							height: 'clamp(6rem, 35vh, 24rem)',
							display: 'flex',
							alignItems: 'center',
							justifyContent: 'center',
						}}
					>
						<div
							style={{
								fontSize: 'clamp(5rem, 26vw, 20rem)',
								lineHeight: 1,
								fontWeight: 700,
								color: '#1e293b',
							}}
						>
							{finalValue ?? '?'}
						</div>
					</div>
				)}
			</div>
		);
	},
);

LinearSpinner.displayName = 'LinearSpinner';

LinearSpinner.propTypes = {
	sides: PropTypes.number,
	onRollComplete: PropTypes.func,
};

export default LinearSpinner;
